baseURL: "//chchwy.github.io/"
languageCode: "zh-tw"
title: "Matt - 調和的靈感"

googleAnalytics: "UA-5266256-5"

pygmentsOptions: []
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  goldmark:
    renderer:
      unsafe: true