base_url = "https://chchwy.github.io"

# The site title and description; used in feeds by default.
title = "調和的靈感 Matt"
description = "紀錄我的思考，讀書筆記，還有程式設計"

# The default language; used in feeds.
default_language = "zh-tw"
compile_sass = false
build_search_index = false
generate_feed = true

# Taxonomies
taxonomies = [
    {name = "tags", feed = true},
    {name = "categories", feed = true}
]

[markdown]
highlight_code = true
highlight_theme = "zenburn"
#highlight_theme = "base16-ocean-dark"

[extra]
# Put all your custom variables here
author = "Matt Chang"
twitter = "@chchwy"
threads = "@chchwy"
github = "chchwy"
