baseURL = ""
languageCode = "zh-tw"
title = "調和的靈感"
disableKinds = ["section", "categories"]
disqusShortname = ""
pygmentsCodeFences = true
pygmentsUseClasses = true
paginate = 9999
minify = true
disableHugoGeneratorInject = true


[taxonomies]
  tag = "tags"
  category = "categories"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[Author]
  name = "chchwy"

[params]
  description = "Minimalistic Hugo blogging theme"
  author = "chchwy"
  copyright = "Copyright © 2021 Matthew Chang"
  logo = ""

[frontmatter]
  date  = [":filename", ":default"]
  author = "chchwy"
  github = "chchwy"
  facebook = ""
  og_image = ""
  sitename = "調和的靈感"
  twitter = ""

[permalinks]
  posts = "/:year/:month/:slug"
  pages = "/:slug"
  photos = "/:year/:month/:day/:filename"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    identifier = "index"
    name       = "Index"
    url        = "/"
    weight     = -111

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects/"
    weight     = -30

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = -20

  [[menu.main]]
    identifier = "tag"
    name       = "Tags"
    url        = "/tagcloud/"
    weight     = -10