base_url = "https://chchwy.github.io"
title = "調和的靈感"
description = "紀錄我的思考、讀書筆記和程式設計紀錄"
author = "chchwy"
default_language = "zh-tw"

generate_feed = true
feed_filename = "atom.xml"
taxonomies = [{ name = "tags", rss = true, paginate_by = 5 }]
theme = "kita"

[markdown]
highlight_code = true

# A list of directories used to search for additional `.sublime-syntax` and `.tmTheme` files.
extra_syntaxes_and_themes = []

# The theme to use for code highlighting.
# See below for list of allowed values.
highlight_theme = "base16-ocean-dark"


[extra]
math = false
mermaid = false
comment = false

[extra.style]
# The custom background color.
bg_color = "#f0e7dd"

# The custom background color in dark mode.
# bg_dark_color = ""

# Enable header blur.
header_blur = true

# The custom header color, only available when `header_blur` is false.
header_color = "#e4dbd2"

# The custom header color in dark mode, only available when `header_blur` is false.
# header_dark_color = ""

# The profile on home page.
[extra.profile]
name = "調和的靈感"
bio = "我的思考、讀書心得、還有程式設計筆記"
avatar_url = "icons/Musqito.jpg"
avatar_invert = true # Invert color in dark mode.

# The social icons below the profile on the home page.
[[extra.profile.social]]
name = "github"
url = "https://github.com/chchwy"

[[extra.profile.social]]
name = "twitter"
url = "https://twitter.com/chchwy"

[[extra.profile.social]]
name = "rss"
url = "$BASE_URL/atom.xml"

# The top menu.
#[[extra.menu]]
#name = "Projects"
#url = "$BASE_URL/projects"

[[extra.menu]]
name = "Archive"
url = "$BASE_URL/archive"

[[extra.menu]]
name = "Tags"
url = "$BASE_URL/tags"

[[extra.menu]]
name = "About"
url = "$BASE_URL/about"

# The page footer options.
[extra.footer]
since = 2024
license = "CC BY-SA 4.0"
license_url = "https://creativecommons.org/licenses/by-sa/4.0/deed"

