name: "Deploy my blog"
on:
  push:
    branches: [ blog ] # 哪些 branch 會觸發 Action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Hugo to Github Pages
    - name: "Publish Hugo Site"
      uses: chabad360/hugo-gh-pages@master
      with:
        branch: "master"
        githubToken: ${{ secrets.PERSONAL_TOKEN }}
